// Importar todos los modelos para asegurar que estén registrados
import './User.model'
import './Course.model'
import './Topic.model'
import './Exam.model'
import './Question.model'
import './Answer.model'
import './ExamResult.model'
import './TopicProgress.model'
import './Membership.model'
import './Payment.model'
import './AIGeneratedContent.model'
import './AIRecommendation.model'
import './Feature.model'

// Re-exportar para facilitar importaciones
export { default as User } from './User.model'
export { default as Course } from './Course.model'
export { default as Topic } from './Topic.model'
export { default as Exam } from './Exam.model'
export { default as Question } from './Question.model'
export { default as Answer } from './Answer.model'
export { default as ExamResult } from './ExamResult.model'
export { default as TopicProgress } from './TopicProgress.model'
export { default as Membership } from './Membership.model'
export { default as Payment } from './Payment.model'
export { default as AIGeneratedContent } from './AIGeneratedContent.model'
export { default as AIRecommendation } from './AIRecommendation.model'
export { default as Feature } from './Feature.model'

